backend:
  name: github
  name: stefanledin/gatsby-netlify-cms-test

media_folder: static/assets
public_folder: /assets

collections:
  - name: project
    label: Projects
    folder: projects
    create: true
    fields:
      - {name: customer, label: Kund}